### ISSUE TITLE
Remove Factory monkey patch ?

### ISSUE THREAD

**Issue by ggrossetie** [asciidoctor/asciidoctor-template.js#12]
@mojavelinux The only remaining reason for it, is that the following code is throwing an exception:

https://github.com/asciidoctor/asciidoctor/blob/v1.5.6.1/lib/asciidoctor/converter/factory.rb#L45-L55

I don't know why (yet) but the following exception is thrown:

```js
err { Cache: uninitialized constant ThreadSafe::Cache
  name: 'Cache',
  message: 'uninitialized constant ThreadSafe::Cache' }
```

More specifically the following code throws the exception:
```js
Opal.const_get_qualified(Opal.const_get_qualified('::', 'ThreadSafe'), 'Cache');
```

For reference, here's the hack implementation: https://github.com/asciidoctor/asciidoctor.js/blob/master/lib/asciidoctor/js/opal_ext/thread_safe.rb

**Comment by mojavelinux** [comment]
:+1:
