### ISSUE TITLE
Do not use File.directory? method when resolving template 

### ISSUE THREAD

**Issue by ggrossetie** [asciidoctor/asciidoctor-template.js#2]
Browsers are unable to implement this method and therefore `resolve_template` method will always returns `nil`.

I think we should try to read template files at:
- `"#{template_dir}/#{name}.#{engine}"`
- `"#{template_dir}/#{engine}/#{name}.#{engine}"`
- `"#{template_dir}/#{backend}/#{name}.#{engine}"`
- `"#{template_dir}/#{engine}/#{backend}/#{name}.#{engine}"`

using only `File.exist?`.

**Comment by mojavelinux** [comment]
I'd even suggest that we make it more restrictive. Let's look for the template at exactly one place and just get people to adhere to that. I think we should just assume the template directory points to where the templates are and not try to go deeper (so the first location). That design was intended more for the Ruby side where you are toggling backends, template engines, and such.
